language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

cache:
  directories:
    - $GOPATH/pkg/mod
    - $GOPATH/bin

install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - go test -v -coverprofile=coverage.txt ./...
  - golangci-lint -v run

after_success:
  - bash <(curl -s https://codecov.io/bash)